### ISSUE TITLE
Model injection is not working in v1.3.2

### ISSUE THREAD

**Issue by angelinuxx** [GrapeoffJS/kindagoose#117]
## Description

By following step by step the example in your documentation, using `User.find()` into the Service throws the following error
```
TypeError: this.userModel.find is not a function
2023-04-12T17:08:04.155289766Z     at UsersService.getAll (/usr/src/service/src/users/users.service.ts:17:27)
2023-04-12T17:08:04.155302730Z     at UsersController.findAll (/usr/src/service/src/users/users.controller.ts:11:30)
2023-04-12T17:08:04.155315409Z     at /usr/src/service/node_modules/@nestjs/core/router/router-execution-context.js:38:29
2023-04-12T17:08:04.155326043Z     at InterceptorsConsumer.intercept (/usr/src/service/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
2023-04-12T17:08:04.155338543Z     at /usr/src/service/node_modules/@nestjs/core/router/router-execution-context.js:46:60
2023-04-12T17:08:04.155352533Z     at /usr/src/service/node_modules/@nestjs/core/router/router-proxy.js:9:23
2023-04-12T17:08:04.155365036Z     at Layer.handle [as handle_request] (/usr/src/service/node_modules/express/lib/router/layer.js:95:5)
2023-04-12T17:08:04.155377325Z     at next (/usr/src/service/node_modules/express/lib/router/route.js:144:13)
2023-04-12T17:08:04.155387628Z     at Route.dispatch (/usr/src/service/node_modules/express/lib/router/route.js:114:3)
2023-04-12T17:08:04.155397801Z     at Layer.handle [as handle_request] (/usr/src/service/node_modules/express/lib/router/layer.js:95:5)
```

This seems to be related to the fix of #114 
Downgrading to v1.3.1 or commenting out in modelFactory the following code restores functionality.

```
const existingModel = discoveryService
      .getProviders()
      .find(provider => provider.token === (0, get_model_token_1.getModelToken)(schema.name, connectionName));
if (existingModel) {
    return existingModel;
}
```

**Comment by GrapeoffJS** [comment]
@angelinuxx Got it. I'll handle with this tomorrow.

**Comment by GrapeoffJS** [comment]
Oh, ok, found the cause right here. The error caused because the following code returns the provider itself instead of its instance (Pure NestJS provider, instead of the value that you place in `useValue`). 

```typescript
if (existingModel) {
    return existingModel;
}
```

https://github.com/GrapeoffJS/kindagoose/releases/tag/1.3.4

I apologize for the inconvenience.

**Comment by angelinuxx** [comment]
Thank you for such a rapid resolution!
